apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: my-test-app
  namespace: default
spec:
  secretName: my-test-app-crt
  commonName: test.platyplus.io
  dnsNames:
  - test.platyplus.io
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - test.platyplus.io